In [24]:
faqs="""Breakfast is often hailed as the most important meal of the day, providing the fuel our bodies need after a night of rest and setting the tone for our energy levels, focus, and mood throughout the morning. A nutritious breakfast can have numerous health benefits, impacting physical well-being, cognitive performance, and overall daily productivity. Typically, breakfast replenishes glucose levels, offering a crucial energy boost essential for engaging in morning activities and staying alert. Studies reveal that a balanced breakfast, one containing carbohydrates, proteins, and healthy fats, can improve cognitive functions like memory and concentration. This is particularly beneficial for students and working professionals, as it enhances mental performance, allowing them to retain information more effectively and stay focused. Skipping breakfast, however, may lead to sluggishness and irritability, as blood sugar levels remain low, impairing cognitive ability and diminishing one’s ability to handle tasks efficiently. For those managing weight, breakfast plays an important role in controlling appetite throughout the day. When people skip breakfast, they often overcompensate by eating larger portions at subsequent meals or snacking on high-calorie foods to curb hunger, which can contribute to unhealthy weight gain. Including protein-rich foods like eggs, Greek yogurt, or nuts, alongside whole grains and fruits, not only curbs hunger but also stabilizes energy, ensuring a slower release of sugar into the bloodstream. Moreover, people who regularly eat breakfast tend to make healthier food choices throughout the day, as breakfast can help regulate cravings and reduce impulsive eating. Another significant benefit of breakfast is its positive impact on metabolic rate. When we eat in the morning, our metabolism kicks in, aiding in better digestion and nutrient absorption. A high-fiber breakfast, such as oatmeal or whole-grain toast, supports digestive health by promoting regular bowel movements and preventing constipation, which is vital for overall gut health. Furthermore, breakfast foods can vary greatly to accommodate dietary restrictions, cultural differences, and personal preferences. For example, a traditional Western breakfast might include cereals, eggs, or toast, while in Asian cultures, breakfast could consist of rice dishes, soups, or dumplings. Although breakfast habits vary, the core goal remains the same: to provide the body with essential nutrients to begin the day. Additionally, breakfast can be an opportunity to include important vitamins and minerals, as people are more likely to consume fruits, vegetables, and dairy in the morning. This can contribute to meeting the recommended daily intake of calcium, iron, and vitamins B and C, which are essential for maintaining bone health, muscle function, and immune response. There is also a social aspect to breakfast; sharing a morning meal with family or friends can foster a sense of connection and well-being. This routine allows individuals to start the day on a positive note, often encouraging mindful eating habits and making breakfast a moment to pause before the demands of the day take over. For many people, however, busy lifestyles make it challenging to fit in a proper breakfast. Despite time constraints, breakfast can be made more accessible with quick yet nutritious options such as smoothies, whole-grain muffins, or breakfast bars. Ultimately, breakfast is a powerful tool for enhancing health, managing weight, and promoting mental clarity and productivity. Whether enjoyed leisurely or on the go, a well-balanced breakfast contributes substantially to one's physical and mental health, underscoring why it remains such a fundamental part of a healthy lifestyle."""

In [25]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [26]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts([faqs])

In [49]:
tokenizer.word_index

{'and': 1,
 'breakfast': 2,
 'the': 3,
 'a': 4,
 'to': 5,
 'of': 6,
 'for': 7,
 'can': 8,
 'in': 9,
 'or': 10,
 'as': 11,
 'is': 12,
 'day': 13,
 'health': 14,
 'morning': 15,
 'people': 16,
 'on': 17,
 'often': 18,
 'important': 19,
 'our': 20,
 'energy': 21,
 'levels': 22,
 'throughout': 23,
 'well': 24,
 'cognitive': 25,
 'essential': 26,
 'this': 27,
 'it': 28,
 'mental': 29,
 'more': 30,
 'weight': 31,
 'eating': 32,
 'foods': 33,
 'which': 34,
 'whole': 35,
 'such': 36,
 'with': 37,
 'meal': 38,
 'nutritious': 39,
 'physical': 40,
 'being': 41,
 'performance': 42,
 'overall': 43,
 'daily': 44,
 'productivity': 45,
 'balanced': 46,
 'healthy': 47,
 'like': 48,
 'however': 49,
 'sugar': 50,
 'ability': 51,
 'managing': 52,
 'an': 53,
 'when': 54,
 'by': 55,
 'high': 56,
 'hunger': 57,
 'contribute': 58,
 'eggs': 59,
 'fruits': 60,
 'also': 61,
 'eat': 62,
 'make': 63,
 'positive': 64,
 'grain': 65,
 'toast': 66,
 'promoting': 67,
 'vary': 68,
 'include': 69,
 'habits': 70,
 'remain

In [31]:
input_sequences=[]
for sentence in faqs.split('.'):
    tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0]
    print(tokenized_sentence)
    for i in range(1,len(tokenized_sentence)):
        input_sequences.append(tokenized_sentence[:i+1])

        
    

[2, 12, 18, 75, 11, 3, 76, 19, 38, 6, 3, 13, 77, 3, 78, 20, 79, 80, 81, 4, 82, 6, 83, 1, 84, 3, 85, 7, 20, 21, 22, 86, 1, 87, 23, 3, 15]
[4, 39, 2, 8, 88, 89, 14, 90, 91, 40, 24, 41, 25, 42, 1, 43, 44, 45]
[92, 2, 93, 94, 22, 95, 4, 96, 21, 97, 26, 7, 98, 9, 15, 99, 1, 100, 101]
[102, 103, 104, 4, 46, 2, 105, 106, 107, 108, 1, 47, 109, 8, 110, 25, 111, 48, 112, 1, 113]
[27, 12, 114, 115, 7, 116, 1, 117, 118, 11, 28, 119, 29, 42, 120, 121, 5, 122, 123, 30, 124, 1, 125, 126]
[127, 2, 49, 128, 129, 5, 130, 1, 131, 11, 132, 50, 22, 133, 134, 135, 25, 51, 1, 136, 137, 51, 5, 138, 139, 140]
[7, 141, 52, 31, 2, 142, 53, 19, 143, 9, 144, 145, 23, 3, 13]
[54, 16, 146, 2, 147, 18, 148, 55, 32, 149, 150, 151, 152, 153, 10, 154, 17, 56, 155, 33, 5, 156, 57, 34, 8, 58, 5, 157, 31, 158]
[159, 160, 161, 33, 48, 59, 162, 163, 10, 164, 165, 35, 166, 1, 60, 167, 168, 169, 57, 170, 61, 171, 21, 172, 4, 173, 174, 6, 50, 175, 3, 176]
[177, 16, 178, 179, 62, 2, 180, 5, 63, 181, 182, 183, 23, 3, 13, 11, 2, 8

In [32]:
print(input_sequences)

[[2, 12], [2, 12, 18], [2, 12, 18, 75], [2, 12, 18, 75, 11], [2, 12, 18, 75, 11, 3], [2, 12, 18, 75, 11, 3, 76], [2, 12, 18, 75, 11, 3, 76, 19], [2, 12, 18, 75, 11, 3, 76, 19, 38], [2, 12, 18, 75, 11, 3, 76, 19, 38, 6], [2, 12, 18, 75, 11, 3, 76, 19, 38, 6, 3], [2, 12, 18, 75, 11, 3, 76, 19, 38, 6, 3, 13], [2, 12, 18, 75, 11, 3, 76, 19, 38, 6, 3, 13, 77], [2, 12, 18, 75, 11, 3, 76, 19, 38, 6, 3, 13, 77, 3], [2, 12, 18, 75, 11, 3, 76, 19, 38, 6, 3, 13, 77, 3, 78], [2, 12, 18, 75, 11, 3, 76, 19, 38, 6, 3, 13, 77, 3, 78, 20], [2, 12, 18, 75, 11, 3, 76, 19, 38, 6, 3, 13, 77, 3, 78, 20, 79], [2, 12, 18, 75, 11, 3, 76, 19, 38, 6, 3, 13, 77, 3, 78, 20, 79, 80], [2, 12, 18, 75, 11, 3, 76, 19, 38, 6, 3, 13, 77, 3, 78, 20, 79, 80, 81], [2, 12, 18, 75, 11, 3, 76, 19, 38, 6, 3, 13, 77, 3, 78, 20, 79, 80, 81, 4], [2, 12, 18, 75, 11, 3, 76, 19, 38, 6, 3, 13, 77, 3, 78, 20, 79, 80, 81, 4, 82], [2, 12, 18, 75, 11, 3, 76, 19, 38, 6, 3, 13, 77, 3, 78, 20, 79, 80, 81, 4, 82, 6], [2, 12, 18, 75, 11, 3, 76

In [36]:
max_len=max([len(x) for x in input_sequences])

In [38]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [40]:
padded_input_sequences=pad_sequences(input_sequences,maxlen=max_len,padding='pre')

In [41]:
print(padded_input_sequences)

[[  0   0   0 ...   0   2  12]
 [  0   0   0 ...   2  12  18]
 [  0   0   0 ...  12  18  75]
 ...
 [  0   0   0 ... 321   6   4]
 [  0   0   0 ...   6   4  47]
 [  0   0   0 ...   4  47 322]]


In [42]:
x=padded_input_sequences[:,:-1]

In [43]:
print(x)

[[  0   0   0 ...   0   0   2]
 [  0   0   0 ...   0   2  12]
 [  0   0   0 ...   2  12  18]
 ...
 [  0   0   0 ... 320 321   6]
 [  0   0   0 ... 321   6   4]
 [  0   0   0 ...   6   4  47]]


In [44]:
y=padded_input_sequences[:,-1]

In [45]:
print(y)

[ 12  18  75  11   3  76  19  38   6   3  13  77   3  78  20  79  80  81
   4  82   6  83   1  84   3  85   7  20  21  22  86   1  87  23   3  15
  39   2   8  88  89  14  90  91  40  24  41  25  42   1  43  44  45   2
  93  94  22  95   4  96  21  97  26   7  98   9  15  99   1 100 101 103
 104   4  46   2 105 106 107 108   1  47 109   8 110  25 111  48 112   1
 113  12 114 115   7 116   1 117 118  11  28 119  29  42 120 121   5 122
 123  30 124   1 125 126   2  49 128 129   5 130   1 131  11 132  50  22
 133 134 135  25  51   1 136 137  51   5 138 139 140 141  52  31   2 142
  53  19 143   9 144 145  23   3  13  16 146   2 147  18 148  55  32 149
 150 151 152 153  10 154  17  56 155  33   5 156  57  34   8  58   5 157
  31 158 160 161  33  48  59 162 163  10 164 165  35 166   1  60 167 168
 169  57 170  61 171  21 172   4 173 174   6  50 175   3 176  16 178 179
  62   2 180   5  63 181 182 183  23   3  13  11   2   8 184 185 186   1
 187 188  32 190 191   6   2  12 192  64 193  17 19

In [46]:
x.shape

(540, 36)

In [47]:
y.shape

(540,)

In [50]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=323)

In [51]:
y.shape

(540, 323)

In [52]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [77]:
model=Sequential()
model.add(Embedding(input_dim=323,output_dim=100,input_length=36,input_shape=(36,)))
model.add(LSTM(150))
model.add(Dense(323,activation='softmax'))

c:\Users\ayush\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
c:\Users\ayush\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [78]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [79]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ (None, 36, 100)        │        32,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_8 (LSTM)                   │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 323)            │        48,773 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 231,673 (904.97 KB)

 Trainable params: 231,673 (904.97 KB)

 Non-trainable params: 0 (0.00 B)

In [80]:
model.fit(x,y,epochs=100)

Epoch 1/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.0365 - loss: 5.7605
Epoch 2/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0366 - loss: 5.4731 
Epoch 3/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0610 - loss: 5.3300
Epoch 4/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0750 - loss: 5.2071
Epoch 5/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0670 - loss: 5.2031
Epoch 6/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0748 - loss: 5.1500
Epoch 7/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0645 - loss: 5.0858
Epoch 8/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0690 - loss: 4.9286
Epoch 9/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0541 - loss: 4.9141 
Epoch 10/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0869 - loss: 4.7571
Epoch 11/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0951 - loss: 4.5925
Epoch 12/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/st

In [83]:
text="Breakfast"  #tokenize,padding,predict
token_text=tokenizer.texts_to_sequences([text])[0]
padded_token_text=pad_sequences([token_text],maxlen=36,padding='pre')
print(padded_token_text)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2]]


In [85]:
model.predict(padded_token_text).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


(1, 323)

In [89]:
import numpy as np
pos=np.argmax(model.predict(padded_token_text))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


In [90]:
for word,index in tokenizer.word_index.items():
    if index==pos:
        print(word)

is


In [93]:
import time
for i in range(5):
    token_text=tokenizer.texts_to_sequences([text])[0]
    padded_token_text=pad_sequences([token_text],maxlen=36,padding='pre')
    pos=np.argmax(model.predict(padded_token_text))
    for word,index in tokenizer.word_index.items():
        if index==pos:
            text=text+" "+word
            print(text)
            time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
Breakfast is often hailed as the most important meal of the day
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
Breakfast is often hailed as the most important meal of the day providing
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
Breakfast is often hailed as the most important meal of the day providing the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
Breakfast is often hailed as the most important meal of the day providing the fuel
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
Breakfast is often hailed as the most important meal of the day providing the fuel our
